GEMINI_BTC_USD_SYMBOL = "BTCUSD"
COINBASE_BTC_USD_SYMBOL = "BTC-USD"
KRAKEN_BTC_USD_SYMBOL = "XBTUSD"
COINROUTES_BTC_USD = "BTCUSD"

KRAKEN_BTC_USD_RESULTS_SYMBOL = "XXBTZUSD"

COINROUTES_GET_PRICE_CHOICES = [COINROUTES_BTC_USD]

COINROUTES_SYMBOL_TO_GEMINI_SYMBOL = {COINROUTES_BTC_USD: GEMINI_BTC_USD_SYMBOL}
COINROUTES_SYMBOL_TO_COINBASE_SYMBOL = {COINROUTES_BTC_USD: COINBASE_BTC_USD_SYMBOL}
COINROUTES_SYMBOL_TO_KRAKEN_SYMBOL = {COINROUTES_BTC_USD: KRAKEN_BTC_USD_SYMBOL}

KRAKEN_REQUEST_SYMBOL_TO_RESULTS_SYMBOL = {
    KRAKEN_BTC_USD_SYMBOL: KRAKEN_BTC_USD_RESULTS_SYMBOL
}


COINBASE = "COINBASE"
KRAKEN = "KRAKEN"
GEMINI = "GEMINI"

